# Generated by Django 4.1.3 on 2022-12-16 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_context'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moshin',
            old_name='content',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
    ]
